### ISSUE TITLE
me sale error TypeError: Cannot read properties of undefined (reading 'flow') AYUDA

### ISSUE THREAD

**Issue by mitre88** [leifermendez/bot-ws-openai#6]
Proveedor conectado y listo

🤖 voz a texto....
🤖 Fin voz a texto....[TEXT]: Hola, buenas noches.
------------>
_____ {
  tool: 'NOT_EMPLOYEE',
  answer: 'not employee',
  log: '[NOT_EMPLOYEE]: not employee'
}
/Users/mitre/Desktop/bot-ws-openai-master/node_modules/bot-ws-plugin-openai/src/plugin.employees.js:76
    const flow = employee.flow
                          ^

TypeError: Cannot read properties of undefined (reading 'flow')
    at EmployeesClass.gotoFlow (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/bot-ws-plugin-openai/src/plugin.employees.js:76:27)
    at Object.ans_dab479ca-c2fa-4e1b-930a-07cb7c410141 (/Users/mitre/Desktop/bot-ws-openai-master/app.js:47:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runContext (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:1444:17)
    at async cbEveryCtx (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:1471:13)
    at async resolveCbEveryCtx (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:1401:29)
    at async Object.promiseInFunc (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:1238:25)
    at async /Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:529:35
    at async Promise.allSettled (index 0)
    at async Queue.processQueue (/Users/mitre/Desktop/bot-ws-openai-master/node_modules/@bot-whatsapp/bot/lib/bundle.bot.cjs:547:13)

Node.js v19.2.0
(base) MacBook-Air-de-Dr-Alex-Mitre:bot-ws-openai-master mitre$

**Comment by DavidKingV** [comment]
Pudiste solucionarlo? estoy en las mismas
